_BASE_: "Base-DiffusionDet.yaml"
MODEL:
  WEIGHTS: "models/swin_base_patch4_window7_224_22k.pkl"
  BACKBONE:
    NAME: build_swintransformer_fpn_backbone
  SWIN:
    SIZE: B-22k
  FPN:
    IN_FEATURES: ["swin0", "swin1", "swin2", "swin3"]
  DiffusionDet:
    NUM_PROPOSALS: 300
    NUM_CLASSES: 1
DATASETS:
  TRAIN: ("pothole_train",)
  TEST: ("pothole_val",)
SOLVER:
  IMS_PER_BATCH: 1
  STEPS: (350000, 420000)
  MAX_ITER: 50000
INPUT:
  MIN_SIZE_TRAIN: (480, 512, 544, 576, 608, 640, 672, 704, 720)
  CROP:
    ENABLED: True
  FORMAT: "RGB"
TEST:
  EVAL_PERIOD: 10000
